name: Scrape Naver Game Lounge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # 매일 14:00 KST

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dateutil

      - name: Run Lounge scraper
        env:
          LOUNGE_LIMIT: '20'
        run: |
          python scripts/scrape_lounge.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add data/updates.json
            git commit -m "chore(ci): auto-update Naver Game Lounge events (cron)"
            git push
          else
            echo "No changes to commit"
          fi


